import {
    j1,
    j2,
    j3,
    sale1,
    sale2,
    sale3,
    sale4,
    sale5,
    ad,
    tr3,
    tr5,
} from '../assets/pricing';

export const pricing = [
    {
        id: 1,
        type: "split type",
        brand: "AUX",
        model: "F-series",
        title: 'AUX F-series 2.0HP',
        code: "ASW18A2/FLDI Inverter",
        srp: 46_799,
        discounted: 34_500,
        image: sale1,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 2,
        type: "split type",
        brand: "AUX",
        model: "F-series",
        title: 'AUX F-series 1.5HP',
        code: "ASW12A2/FLDI Inverter",
        srp: 36_299,
        discounted: 27_950,
        image: sale2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 3,
        type: "split type",
        brand: "AUX",
        model: "F-series",
        title: 'AUX F-series 2.5HP',
        code: "ASW24A2/FLDI Inverter",
        srp: 56_199,
        discounted: 41_500,
        image: sale3,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 4,
        type: "split type",
        brand: "AUX",
        model: "F-series",
        title: 'AUX F-series 1.0HP',
        code: "ASW09A2/FLDI Inverter",
        srp: 32_299,
        discounted: 25_500,
        image: sale4,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 5,
        type: "split type",
        brand: "AUX",
        model: "F-series",
        title: 'AUX F-series 3.0HP',
        code: "ASW30A2/FLDI Inverter",
        srp: 60_799,
        discounted: 45_500,
        image: sale5,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 6,
        type: "split type",
        brand: "AUX",
        model: "J-Smart Series",
        title: 'AUX J-Smart Series 1.0HP ',
        code: "ASW09A2/JADI",
        srp: 34_999,
        discounted: 27_500,
        image: j2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 7,
        type: "split type",
        brand: "AUX",
        model: "J-Smart Series",
        title: 'AUX J-Smart Series 1.5HP',
        code: "ASW12A2/JADI",
        srp: 39_199,
        discounted: 31_500,
        image: j2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 8,
        type: "split type",
        brand: "AUX",
        model: "J-Smart Series",
        title: 'AUX J-Smart Series 2.0HP',
        code: "ASW18A2/JADI",
        srp: 49_799,
        discounted: 37_500,
        image: j2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 9,
        type: "floor standing",
        brand: "AUX",
        model: "floor standing",
        title: 'AUX TR3',
        code: "ASW36A2/APADI",
        hp: "3TR",
        srp: 116_699,
        discounted: 99_000,
        image: tr3,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
        id: 10,
        type: "floor standing",
        brand: "AUX",
        model: "floor standing",
        title: 'AUX TR5',
        code: "ASW60A2/APADI",
        hp: "5TR",
        srp: 147_999,
        discounted: 133_000,
        image: tr5,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
]